spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: out
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      transaction-id-prefix: tx-
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa.hibernate.ddl-auto: none

  flyway:
    baselineOnMigrate: true
    locations:
      - db/migration

logging:
  level.root: ERROR
  level:
    org.springframework.kafka.transaction: trace
    org.springframework.kafka.core.DefaultKafkaProducerFactory: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
    org.springframework.kafka.transaction.KafkaTransactionManager: debug